Repository NativeScript/android, pull requests merged in 2019-03, with the labels that each got.

#1294 Run tests on multiple emulators
  .travis.yml
  build.sh
  test-app/app/src/main/assets/app/tests/testArrays.js
  test-app/app/src/main/assets/app/tests/tests.js
Labels: cla: yes

#1299 Build generators in separate builds
  test-app/app/build.gradle
  test-app/build-tools/android-metadata-generator/build.gradle
  test-app/build-tools/static-binding-generator/build.gradle
Labels: cla: yes

#1300 updated lodash dependency to fix security alert
  test-app/build-tools/jsparser/package-lock.json
Labels: cla: yes

#1305 Update android gradle plugin to 3.3.2
  package.json
  test-app/build-tools/android-metadata-generator/build.gradle
  test-app/build.gradle
Labels: cla: yes

#1307 Refactor build.gradle not to add configuration:'default'
  test-app/app/build.gradle
  test-app/runtime/build.gradle
Labels: cla: yes

#1308 fix(gradle): Fix `runSbg` and `collectAllJars` tasks' dependencies
  test-app/app/build.gradle
Labels: bug, cla: yes, improvement

#1313 chore: remove min/target SdkVersion from manifest
  .travis.yml
  build-artifacts/project-template-gradle/app/src/main/AndroidManifest.xml
Labels: cla: yes

#1318 fix(gradle): Change outputs directory of runSbg
  test-app/app/build.gradle
Labels: bug, cla: yes

#1321 Use again android.app.Activity as it is support/x independent
  test-app/app/src/main/assets/app/MyActivity.js
  test-app/build-tools/jsparser/tests/cases/decorated_double_assignment_ts/app/myCustomActivity.android.ts
  test-app/build-tools/jsparser/tests/cases/decorated_double_assignment_ts/app/myCustomActivity_ts.android.js
Labels: cla: yes

#1323 Improve handling of nested Java class name writing
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/classes/hierarchy/generics/impl/GenericsAwareClassHierarchyParserImpl.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/impl/MethodSignatureReifier.java
  test-app/build-tools/static-binding-generator/src/test/java/org/nativescript/staticbindinggenerator/generating/parsing/classes/hierarchy/generics/impl/GenericsAwareClassHierarchyParserImplTest.java
Labels: cla: yes

#1327 Fix issues with generic methods handling in the SBG
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/Generator.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/Main.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/files/FileSystemHelper.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/files/impl/ClassesCollection.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/files/impl/FileSystemHelperImpl.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/classes/hierarchy/generics/impl/GenericSignatureReader.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/classes/hierarchy/generics/impl/GenericsAwareClassHierarchyParserImpl.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/classes/hierarchy/impl/ClassHierarchyParserImpl.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/JavaMethod.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/ReifiedJavaMethod.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/generics/MethodDeclarationTransformation.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/generics/MethodReificationPipeline.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/generics/impl/ArgumentsDeclarationReificationTransformation.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/generics/impl/MethodReificationPipelineImpl.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/generics/impl/OwnTypeParametersDeclarationTransformation.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/generics/impl/ReturnTypeDeclarationReificationTransformation.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/generics/impl/WildcardBoundsTransformation.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/impl/InheritedMethodsCollectorImpl.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/impl/JavaClassUtils.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/impl/JavaMethodImpl.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/impl/JavaMethodUtils.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/impl/MethodSignatureReifier.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/parsing/methods/impl/ReifiedJavaMethodImpl.java
  test-app/build-tools/static-binding-generator/src/main/java/org/nativescript/staticbindinggenerator/generating/writing/impl/MethodsWriterImpl.java
  test-app/build-tools/static-binding-generator/src/test/java/org/nativescript/staticbindinggenerator/generating/parsing/classes/hierarchy/generics/impl/GenericsAwareClassHierarchyParserImplTest.java
  test-app/build-tools/static-binding-generator/src/test/java/org/nativescript/staticbindinggenerator/generating/parsing/classes/hierarchy/generics/impl/test3/Base.java
  test-app/build-tools/static-binding-generator/src/test/java/org/nativescript/staticbindinggenerator/generating/parsing/classes/hierarchy/generics/impl/test3/Concrete.java
Labels: cla: yes
